package fil_rouge.Enums;

public enum Region {

    TANGER_TETOUAN_ALHOCEIMA,
    ORIENTAL,
    FES_MEKNES,
    RABAT_SALE_KENITRA,
    BENIMELLAL_KHENIFRA,
    CASABLANCA_SETTAT,
    MARRAKECH_SAFI,
    DRAA_TAFILALET,
    SOUSS_MASSA,
    GUELMIM_OUEDNOUN,
    LAAYOUNE_SAKIA_ELHAMRA,
    DAKHLA_OUED_EDDAHAB

}
