version: '3.8'

services:
  app:
    build: .
    ports:
      - "8097:8097"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/FILROUGE?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=azer@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=azer@123
      - MYSQL_DATABASE=FILROUGE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge